services:

  discord-srv-go:
    build:
      context: ./discord-srv-go
      dockerfile: ./build/Dockerfile.prod
    container_name: discord-srv-go
    restart: always
    environment:
      TIMEZONE: ${TIMEZONE}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      LOG_FILE: ${LOG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      PLAYER_CHECK_INTERVAL: ${PLAYER_CHECK_INTERVAL}
      MC_CONTAINER_NAME: ${MC_CONTAINER_NAME}
      MC_MONITOR_INTERVAL: ${MC_MONITOR_INTERVAL}
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - main-application-network2

  vanilla:
    container_name: mc_vanilla
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ENABLE_ROLLING_LOGS: ${ENABLE_ROLLING_LOGS}
      JVM_OPTS: ${JVM_OPTS}
      EULA: ${EULA}
      MOTD: ${MOTD}
      SEED: ${SEED}
      DIFFICULTY: ${DIFFICULTY}
      MAX_PLAYERS: ${MAX_PLAYERS}
      MAX_WORLD_SIZE: ${MAX_WORLD_SIZE}
      ENABLE_COMMAND_BLOCK: ${ENABLE_COMMAND_BLOCK}
      SNOOPER_ENABLED: ${SNOOPER_ENABLED}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      PVP: ${PVP}
      LEVEL: ${LEVEL}
      VERSION: ${VERSION}
      MODE: ${MODE}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT}
      USE_NATIVE_TRANSPORT: ${USE_NATIVE_TRANSPORT}
      SIMULATION_DISTANCE: ${SIMULATION_DISTANCE}
      STOP_SERVER_ANNOUNCE_DELAY: ${STOP_SERVER_ANNOUNCE_DELAY}
      GUI: ${GUI}
      SPAWN_PROTECTION: ${SPAWN_PROTECTION}
      ENABLE_RCON: ${ENABLE_RCON}
      RCON_PORT: ${RCON_PORT}
      RCON_PASSWORD: ${RCON_PASSWORD}
    ports:
      - "${MC_SERVER_PORT}:25565/tcp"
      - "${MC_SERVER_PORT}:25565/udp"
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
    restart: always
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 10
    depends_on:
      - discord-srv-go
    networks:
      - main-application-network2
  
  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      RCON_HOST: ${RCON_HOST}
      RCON_PORT: ${RCON_PORT}
      PRUNE_BACKUPS_DAYS: ${PRUNE_BACKUPS_DAYS}
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data:ro
      - ${MINECRAFT_BACKUP_DATA_PATH}:/backups
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - vanilla
    networks:
      - main-application-network2

networks:
  main-application-network2:
    external: true
    
