services:
  golang:
    build:
      context: .
      dockerfile: ./build/Dockerfile.dev
    tty: true
    stdin_open: true
    container_name: ${GOLANG_CONTAINER_NAME}
    restart: always
    environment:
      TIMEZONE: ${TIMEZONE}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      LOG_FILE: ${LOG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      PLAYER_CHECK_INTERVAL: ${PLAYER_CHECK_INTERVAL}
      MC_SERVER_HOST: ${MC_SERVER_HOST}
      MC_SERVER_PORT: ${MC_SERVER_PORT}
      MC_MONITOR_INTERVAL: ${MC_MONITOR_INTERVAL}
    volumes:
      - ./:${WORKDIR_PATH}
      - ${MINECRAFT_DATA_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - main-application-network2

networks:
  main-application-network2:
    external: true