services:
  golang:
    build:
      context: .
      dockerfile: ./build/Dockerfile.dev
    tty: true
    stdin_open: true
    container_name: ${GOLANG_CONTAINER_NAME}
    restart: always
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      LOG_FILE: ${LOG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      HEALTH_INTERVAL: ${HEALTH_INTERVAL}
    volumes:
      - ./:${GOLANG_ROOT_PATH}
      - ${MINECRAFT_DATA_PATH}:/data
    networks:
      - main-application-network2

networks:
  main-application-network2:
    external: true