name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23' ]
    defaults:
      run:
        working-directory: ./discord-srv-go
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('discord-srv-go/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Display Go version
      run: go version
    
    - name: Download dependencies
      run: go mod download
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Run vet
      run: go vet ./...
    
    # - name: Run tests
    #   run: go test -v ./...
    
    - name: Check formatting
      run: |
        go fmt ./...
        git diff --exit-code
    
    - name: Build application
      run: go build -v ./pkg/cmd
    
    - name: Run build verification
      run: |
        if [ -f "./pkg/cmd" ]; then
          echo "✅ Build successful - executable created"
          ls -la ./pkg/cmd
        else
          echo "❌ Build failed - no executable found"
          exit 1
        fi
